### PR TITLE
Add DTLS bug patterns

### PR DESCRIPTION
**Pull request by kritonios01**
I have added all non-parametric DTLS server bug patterns as described in the NDSS paper. Also, I added a DTLS integration test and modified a unit-test so that it checks if the bug patterns have been expanded correctly.

### CODE REVIEW

**Comment by kostis** [comment]
Looks good overall, but I am wondering:
-  Didn't the coverage increase (even by a small percentage) with the new test(s)?
-  If yes, shouldn't this be reflected in the relevant place in `pom.xml`?

**Comment by kritonios01** [comment]
The coverage rate has not increased. This makes sense because the main function has already been largely covered by previous integration tests and the functionality that tests for expanded bug patterns has also been covered by Paul's unit-tests. However, still if you take a look at the data there is a tiny increase (so tiny that it is not reflected in the coverage percentage): Missed instructions went down from 7.701 to 7.698 and Missed branches went from 889 down to 886.

**Comment by kostis** [comment]
> The coverage rate has not increased. ....
> However, still if you take a look at the data there is a tiny increase (so tiny that it is not reflected in the coverage percentage)

Perhaps it was my lucky day, but when I run this PR, I get slightly increased coverage (54% -> 55%).

Let me push the relevant change and see whether the tests will succeed or fail with that...

**Comment by kritonios01** [comment]
Really really weird...`index.html` on jacoco-merged still shows 54% but build succeeds with your change. Any way, this could be an issue with how floating point arithmetics are handled in arm compared to x86, but since it works we are good!

**Review by pfg666 — APPROVED** [review]
Looks good!

**Pull request merged**
