### PR TITLE
Integration tests for SSH models

### PR DESCRIPTION
**Pull request by kritonios01**
Please review this pull request and suggest any changes.

### CODE REVIEW

**Review by kostis — COMMENTED** [review]
Looks good overall, but I am not sure why there is commented out code and whether we would (still) want it there (esp. in the `SshCommandsExecIT.java` file).  Are there good reasons to keep these commented out lines?

Also, as the title of the PR says, these are _integration_ tests instead of just _unit_ tests --since my Java development skills are pretty bad, I had to Google about the differences-- they are run separately from them.  This is probably OK, but are we sure they are taken into account when `jacoco` checks for code coverage?  Do we also need to update the number for the coverage achieved now that we have more tests?  (Perhaps @pfg666, who is more proficient in Java than me can comment on this.)

Finally, as you saw, I've committed some changes that shut off warnings.  It's not a good idea to ignore them or end up with a code base that produces warnings.  We try to keep the code base warning-free.  (Perhaps we should enable warnings as errors?)

EDIT: Initially, referred to the wrong file...

**Comment by kritonios01** [comment]
Thank you for your comment.
I believe those commented out lines should stay as they are because they are used for debugging purposes. When the tests are not working as expected these `toString()` functions (found in OutputBug.java and Output.java) help show the user how the expected output and actual output compare. Otherwise, Java just throws an error implying that two objects (the outputs) are not the same.
Integration tests have to be run separately from unit tests, because it is assumed that the program has been compiled first. Otherwise (if they were treated as unit tests), maven would run them before compiling. This works when the project has already been compiled once without these tests, because by the time it is compiled with these tests a binary already exists. But, a `mvn clean install` would always fail! Regarding jacoco: let me check and get back to you.

**Comment by pfg666** [comment]
@kritonios01 To execute system/integration tests from within Java, I suggest you use SMBugFInder's main method (`se.uu.it.smbugfinder.Main::main`), instead of the compiled JAR,. You can supply this method with user arguments. This has the same effect as running the JAR without the technical hurdles. Plus it avoids the jacocco issue (jacacoco will consider code covered by running the main method).

**Review by kostis — APPROVED** [review]
Looks good now -- and can be squashed and merged.

**Pull request merged**
